#!/usr/bin/env php
<?php

if(!file_exists('include/cli_startup.php')) {
	echo 'Run from the top level Hubzilla web directory, as util/cleanup_dead_sites' . PHP_EOL;
	exit(1);
}

require_once('include/cli_startup.php');

cli_startup();

if (isset($argv[1]) && $argv[1] === 'delete') {
	$delete = true;
}

if ($delete) {
	echo '🔴 CLEANUP STARTS IN 3 SECONDS!!!' . PHP_EOL;
}
else {
	echo '🔵 Dry run starts in 3 seconds!' . PHP_EOL;
	echo '️🔵 Use "util/cleanup_dead_sites delete" to perform the cleanup.' . PHP_EOL;
}

echo PHP_EOL;
sleep(3);

cleanup_dead_sites($delete);

function cleanup_dead_sites($delete = false) {
	$years = 3;

	$sites = q("SELECT site_url, site_type FROM site
		WHERE site_dead = 1
		AND site_pull < %s - INTERVAL %s
		AND site_url <> '%s'
		ORDER BY site_pull
		LIMIT 100",
		db_utcnow(),
		db_quoteinterval($years . ' YEAR'),
		dbesc(z_root())
	);

	if (!$sites) {
		echo('No candidates to process.' . PHP_EOL);
		return;
	}

	$deleted_xchans = 0;
	$deleted_sites = 0;

	foreach($sites as $site) {
		// This should not happen, but check anyway
		if (!strcasecmp($site['site_url'], z_root())) {
			continue;
		}

		echo('🟠 Checking site: ' . $site['site_url'] . PHP_EOL);

		$test = ping_site($site['site_url'], $site['site_type']);

		if ($test['success']) {
			$main_version = preg_split('/[-+]/', $test['version'])[0];
			q("update site set site_dead = 0, site_update = '%s', site_pull = '%s', site_type = %d, site_project = '%s', site_version = '%s' where site_url = '%s'",
				dbesc(datetime_convert()),
				dbesc(datetime_convert()),
				intval($test['type']),
				dbesc($test['project']),
				dbesc($main_version),
				dbesc($site['site_url'])
			);

			echo('❤️ Ping successful, marked site alive: ' . $site['site_url'] . PHP_EOL);
			new_line_and_sleep();
			continue;
		}

		$hublocs = q("SELECT DISTINCT hubloc_hash FROM hubloc WHERE hubloc_url = '%s'",
			dbesc($site['site_url'])
		);

		foreach($hublocs as $hubloc) {
			// See remove_all_xchan_resources()
			echo('️🔵 Checking xchan: ' . $hubloc['hubloc_hash'] . PHP_EOL);

			// If we have other hublocs than the one from the dead site,
			// we can safely remove the dead one.
			$alt_locs = q("SELECT hubloc_hash FROM hubloc WHERE hubloc_hash = '%s' AND hubloc_url != '%s' AND hubloc_deleted = 0 LIMIT 1",
				dbesc($hubloc['hubloc_hash']),
				dbesc($site['site_url'])
			);

			if ($alt_locs) {
				echo('✅ Removing dead hubloc: an active alternative exists: ' . $hubloc['hubloc_hash'] . PHP_EOL);
				if ($delete) {
					q("DELETE FROM hubloc WHERE hubloc_hash = '%s' and hubloc_url = '%s'",
						dbesc($hubloc['hubloc_hash']),
						dbesc($site['site_url'])
					);
				}
				new_line_and_sleep();
				continue;
			}

			// Is it a connection from somebody?
			$r = q("SELECT abook_id FROM abook WHERE abook_xchan = '%s' LIMIT 1",
				dbesc($hubloc['hubloc_hash'])
			);
			if ($r) {
				echo('❌ Skipping xchan: active connection exists: ' . $hubloc['hubloc_hash'] . PHP_EOL);
				new_line_and_sleep();
				continue;
			}

			// Do we have any items?
			$r = q("SELECT id FROM item WHERE author_xchan = '%s' OR owner_xchan = '%s' OR source_xchan = '%s' LIMIT 1",
				dbesc($hubloc['hubloc_hash']),
				dbesc($hubloc['hubloc_hash']),
				dbesc($hubloc['hubloc_hash'])
			);
			if ($r) {
				echo('❌ Skipping xchan: items exist: ' . $hubloc['hubloc_hash'] . PHP_EOL);
				new_line_and_sleep();
				continue;
			}

			// Do we have any photos? Disregard profile images.
			$r = q("SELECT id FROM photo WHERE xchan = '%s' and photo_usage <> %d LIMIT 1",
				dbesc($hubloc['hubloc_hash']),
				intval(PHOTO_XCHAN)
			);
			if ($r) {
				echo('❌ Skipping xchan: photos exist: ' . $hubloc['hubloc_hash'] . PHP_EOL);
				new_line_and_sleep();
				continue;
			}

			// Do we have any events?
			$r = q("SELECT id FROM event WHERE event_xchan = '%s' LIMIT 1",
				dbesc($hubloc['hubloc_hash'])
			);
			if ($r) {
				echo('❌ Skipping xchan: events exist: ' . $hubloc['hubloc_hash'] . PHP_EOL);
				new_line_and_sleep();
				continue;
			}

			// What about addons like cart?
			// Provide a hook to clean up additional resources?

			// If we get here, the xchan resources, hubloc, and xchan should be safe to remove.
			echo('✅ Removing xchan resources: ' . $hubloc['hubloc_hash'] . PHP_EOL);
			if ($delete) {
				remove_all_xchan_resources($hubloc['hubloc_hash']);

				q("DELETE FROM hubloc WHERE hubloc_hash = '%s' and hubloc_url = '%s'",
					dbesc($hubloc['hubloc_hash']),
					dbesc($site['site_url'])
				);

				q("DELETE FROM xchan WHERE xchan_hash = '%s'",
					dbesc($hubloc['hubloc_hash'])
				);
			}

			$deleted_xchans++;
			new_line_and_sleep();
		}

		$remaining = q("SELECT hubloc_hash FROM hubloc WHERE hubloc_url = '%s' LIMIT 1",
			dbesc($site['site_url'])
		);

		// If no hublocs remain, remove the site.
		if (!$remaining) {
			echo('🔥 No hublocs remain, removing site: ' . $site['site_url'] . PHP_EOL);
			if ($delete) {
				q("DELETE FROM site WHERE site_url = '%s'",
					dbesc($site['site_url'])
				);
			}

			$deleted_sites++;
		}
		else {
			if ($delete) {
				// Set site_pull to -35 (one month less than 3 years) before now.
				echo('❌ Hublocs remain, scheduling site for another check in one month: ' . $site['site_url'] . PHP_EOL);

				q("UPDATE site SET site_pull = '%s' WHERE site_url = '%s'",
					dbesc(datetime_convert('UTC', 'UTC', 'now  - 35 months')),
					dbesc($site['site_url'])
				);
			}
		}

		new_line_and_sleep();
	}

	echo('Deleted xchans: ' . $deleted_xchans . PHP_EOL);
	echo('Deleted sites: ' . $deleted_sites . PHP_EOL);
}


function new_line_and_sleep() {
	echo(PHP_EOL);
	sleep(1);
}
